apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    name: ibm-auditwebhook-operator
    app.kubernetes.io/instance: ibm-auditwebhook-operator
    app.kubernetes.io/managed-by: ibm-auditwebhook-operator
    app.kubernetes.io/name: ibm-auditwebhook-operator
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      name: ibm-auditwebhook-operator
      app.kubernetes.io/instance: ibm-auditwebhook-operator
      app.kubernetes.io/managed-by: ibm-auditwebhook-operator
      app.kubernetes.io/name: ibm-auditwebhook-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
        name: ibm-auditwebhook-operator
        app.kubernetes.io/instance: ibm-auditwebhook-operator
        app.kubernetes.io/managed-by: ibm-auditwebhook-operator
        app.kubernetes.io/name: ibm-auditwebhook-operator
        intent: projected
      annotations:
        productName: "ibm-auditwebhook-operator"
        productID: "86798188679816798867988679186791"
        productVersion: "1.0.0"
        productMetric: VIRTUAL_PROCESSOR_CORE
        cloudpakId: "86798188679816798867988679186791"
        cloudpakName: "Cloud Pak Open"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 3
              preference:
                matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        image: controller:latest
        name: manager
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi
      imagePullSecrets:
        - name: cp.stg.icr.io
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
