apiVersion: v1
imagePullSecrets:
- name: cp.stg.icr.io
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: ibm-auditwebhook-operator
    app.kubernetes.io/managed-by: ibm-auditwebhook-operator
    app.kubernetes.io/name: ibm-auditwebhook-operator
    control-plane: controller-manager
  name: cp4d-audit-webhook-operator-controller-manager
