# permissions for end users to view auditwebhooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auditwebhook-viewer-role
rules:
- apiGroups:
  - audit.watson.ibm.com
  resources:
  - auditwebhooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - audit.watson.ibm.com
  resources:
  - auditwebhooks/status
  verbs:
  - get
