# permissions for end users to edit auditwebhooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auditwebhook-editor-role
rules:
- apiGroups:
  - audit.watson.ibm.com
  resources:
  - auditwebhooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - audit.watson.ibm.com
  resources:
  - auditwebhooks/status
  verbs:
  - get
