apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-election-rolebinding
  labels:
    control-plane: controller-manager
    app.kubernetes.io/instance: ibm-auditwebhook-operator
    app.kubernetes.io/managed-by: ibm-auditwebhook-operator
    app.kubernetes.io/name: ibm-auditwebhook-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
