apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Seamless Upgrades
    containerImage: cp.stg.icr.io/cp/opencontent-auditwebhook-operator@sha256:6ffc0b53352517f8da2d62ad6949cef0474b44cd2f506be452a1a3ece199ae72
    description: This is the ibm-auditwebhook-operator's csv file
    operators.operatorframework.io/builder: operator-sdk-v1.6.1+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: cp4d-audit-webhook-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: AuditWebhook is the Schema for the auditwebhooks API
      displayName: Audit Webhook
      kind: AuditWebhook
      name: auditwebhooks.audit.watson.ibm.com
      version: v1beta1
  description: Operator for making logs compliant
  displayName: ibm-audit-webhook-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - audit
  - webhook
  - logs
  links:
  - name: Cp4d Audit Webhook Operator
    url: https://cp4d-audit-webhook-operator.domain
  maturity: alpha
  provider:
    name: IBM
  relatedImages:
  - image: cp.stg.icr.io/cp/opencontent-audit-webhook@sha256:0d8c98939b31aa261d09b9f38f834cf524007cf6af1a6e02198bee115d04f918
    name: opencontent-audit-webhook-v0.1.0
  - image: cp.stg.icr.io/cp/watson/operators/ose-kube-rbac-proxy@sha256:ca290fbe3a0de7ac7a513322d466fd26124c56851c027430a8c1dbe2b30f21f6
    name: ose-kube-rbac-proxy-v4.7
  - image: cp.stg.icr.io/cp/opencontent-auditwebhook-operator@sha256:6ffc0b53352517f8da2d62ad6949cef0474b44cd2f506be452a1a3ece199ae72
    name: opencontent-auditwebhook-operator-latest
  - image: cp.stg.icr.io/cp/opencontent-fluentd@sha256:d71c70d59540caead90cfb46c83ebafe55787078f73e48bf12558f73b997b17e
    name: opencontent-fluentd-ruby-ubi
  version: 0.0.0
