apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: cp4d-audit-webhook-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: AuditWebhook is the Schema for the auditwebhooks API
      displayName: Audit Webhook
      kind: AuditWebhook
      name: auditwebhooks.audit.watson.ibm.com
      version: v1beta1
  description: AuditWebhook is the Schema for the auditwebhooks API
  displayName: Audit Webhook
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - audit
  - webhook
  - logs
  links:
  - name: Cp4d Audit Webhook Operator
    url: https://cp4d-audit-webhook-operator.domain
  maturity: alpha
  provider:
    name: IBM
    url: https://cp4d-audit-webhook-operator.domain
  version: 0.0.0
